### ISSUE TITLE
I know this Vanilla-friendly but I have a quick question.

### ISSUE THREAD

**Issue by TheShadyyOneYT** [Chailotl/early-game-overhaul#5]
just to ask, but could you consider adding a config (Json or ingame) that would allow me or other people to prevent blocks from being obtained from other mods. Granted, I don't want to be making this difficult in any way on your part. I only ask this because similar mods to this don't add a way that is easy enough to disable certain modded blocks from being obtained without proper tools. Or if I'm wrong and something like this is implemented or I'm missing the point of this mod. please enlighten me. But this is fantastic mod! I'm glad to see more early game progression mods out there. (Could also consider Jade/WTHIT support, if not already implemented)

**Comment by Chailotl** [comment]
> could you consider adding a config (Json or ingame) that would allow me or other people to prevent blocks from being obtained from other mods.

This is out of scope for my mod. There may be other mods that can do what you're looking for.

> But this is fantastic mod!

Thank you!

> (Could also consider Jade/WTHIT support, if not already implemented)

Jade and WTHIT work automatically, there is no need for me to write compat for them.
